export const mockData = [
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
	{
		name: "Name",
		description: "This is a mock description of element",
		price: 140.99,
		rating: 4,
	},
];
